apiVersion: v1
kind: Pod
metadata:
  name: sample-pv
spec:
  volumes:
  - name: host-volume
    persistentVolumeClaim:
      claimName: pvc-hostpath
  containers:
  - image: nginx:latest
    name: sample-container
    volumeMounts:
    - name: host-volume
      mountPath: /mydata
