apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-cont
        image: nginx:latest
        ports:
        - containerPort: 80
#
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo Hello from the postStart handler"]
          preStop:
            exec:
              command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]
#
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 60
          successThreshold: 1
#
        resources:
          requests:
            cpu: "150m"
            memory: "100Mi"
          limits:
            cpu: "325m"
            memory: "175Mi"
#
        env:
        - name: JAVA_HOME_PRD
          valueFrom:
            configMapKeyRef:
              name: java-prd
              key: JAVA_HOME_PRD
#
        volumeMounts:
          - name: config-prd
            mountPath: /usr/src/app/config
          - name: my-secret-volume
            mountPath: /usr/src/app/secret
      volumes:
      - name: config-prd
        configMap:
          name: config-prd

        volumeMounts:
          - name: my-secret-volume
            mountPath: /usr/src/app/secret
      - name: my-secret-volume
        secret:
          secretName: my-secret
