apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-deployment
  labels:
    app: sales
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      containers:
      - name: sales-app
        image: nginx:1.9.1
        ports:
        - containerPort: 80
        env:
        - name: JAVA_HOME
          valueFrom:
            configMapKeyRef:
              name: sales-dev
              key: JAVA_HOME
        - name: API_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: sales-dev
              key: API_ENDPOINT
