# To apply all the environment variables from a specific configmap
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-deployment
  labels:
    app: sales
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      containers:
      - name: sales-app
        image: nginx:1.9.1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: special-config
