apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    app: sample
spec:
  containers:
  - name: sample-container
    image: nginx:latest
    env:
    - name: GREETING
      value: "Hello, Welcome to Kubernetes"
