apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
spec:
  hard:
    cpu: "1"
    memory: 700Mi
    pods: "4"
    services: "2"
    secrets: "3"
    count/configmaps: "2"
    count/deployments.apps: "4"
    count/jobs.batch: "5"
    count/cronjobs.batch: "3"
