apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    app: sample
spec:
  containers:
  - name: sample-container
    image: cloudnatived/demo:hello
    securityContext:
      runAsUser: 1234
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowprivilegeEscalation: false
