apiVersion: v1
kind: Service
metadata:  
  name: loadbalancer-service
spec:
  selector:    
    app: nginx-deploy
  type: LoadBalancer
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
