apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-app
  namespace: development
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: sales-app-container
        image: nginx:1.16.1
        resources:         
          limits:          
            cpu: 50m        
            memory: "55Mi"
        env:
          - name: API_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: sales-configmap
                key: API_ENDPOINT 
