apiVersion: v1
kind: Pod
metadata:
  name: emptyvol-pod
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: IfNotPresent
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
