# The emptydir can be mounted to different locations for different containers
# When we share the same emptydir between mutliple containers, they all share the data between each other.

apiVersion: v1
kind: Pod
metadata:
  name: myvolumes-pod
spec:
  containers:
  - image: alpine:latest
    imagePullPolicy: IfNotPresent
    name: myvolumes-container-1 
    command: ['sh', '-c', 'echo The Bench Container 1 is Running ; sleep 3600']
    volumeMounts:
    - mountPath: /demo1
      name: demo-volume

  - image: alpine:latest
    imagePullPolicy: IfNotPresent
    name: myvolumes-container-2
    command: ['sh', '-c', 'echo The Bench Container 2 is Running ; sleep 3600']
    volumeMounts:
    - mountPath: /demo2
      name: demo-volume

  - image: alpine:latest
    imagePullPolicy: IfNotPresent
    name: myvolumes-container-3
    command: ['sh', '-c', 'echo The Bench Container 3 is Running ; sleep 3600']
    volumeMounts:
    - mountPath: /demo3
      name: demo-volume

  volumes:
  - name: demo-volume
    emptyDir: {}
