apiVersion: v1
kind: Pod
metadata:
  name: hostvol-pod
spec:
  containers:
  - image: nginx:latest
    name: test-container
    volumeMounts:
    - mountPath: /test-vol
      name: local-volume
  volumes:
  - name: local-volume
    hostPath:
      # directory location on host server
      path: /data
