apiVersion: v1
kind: Pod
metadata:
 name: mypod
spec:
 volumes:
   - name: my-pv
     persistentVolumeClaim:
       claimName: pv-example
 containers:
   - name: mypod
     image: ubuntu:latest
     command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 1000 ; done"]
     volumeMounts:
       - mountPath: "/app-data"
         name: my-pv
