apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-cont
        image: nginx:1.15.1
        ports:
        - containerPort: 80
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "2xlarge"
        effect: "NoSchedule"
