apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-app
  namespace: development
spec:
  selector:
    matchLabels:
      app: salesapp
  template:
    metadata:
      labels:
        app: salesapp
    spec:
      containers:
      - name: sales-app-container
        image: nginx:1.16.1
        ports:
        - containerPort: 80
        env:
          - name: JAVA_HOME
            valueFrom:
              configMapKeyRef:
                name: sales-configmap
                key: JAVA_HOME 
