apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: demo-apps
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
