apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-deamonset
  labels:
    app: monitor
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: nginx:1.15.1
        ports:
        - containerPort: 80
