apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-cont
        image: nginx:1.9.1
        ports:
        - containerPort: 80
        env:
          - name: username
            valueFrom:
              secretKeyRef:
                name: sales-creds
                key: username
          - name: password
            valueFrom:
              secretKeyRef:
                name: sales-creds
                key: password
