apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: sales-app
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sales-app
  template:
    metadata:
      labels:
        app: sales-app
    spec:
      containers:
      - name: nginx-rs
        image: nginx:latest
        resources:
          limits:
            cpu: 200m
            memory: "105Mi"
